// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSiteAssignment2.Models;

namespace WebSiteAssignment2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAssignment.Models.Band", b =>
                {
                    b.Property<int>("BandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BandGenre")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("BandDescription")
                        .HasColumnType("text");

                    b.Property<string>("BandImage")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("GigDate")
                        .HasColumnType("datetime2");


                    b.HasKey("BandID");

                    b.ToTable("Bands");
                });
#pragma warning restore 612, 618
        }
    }
}
